[project]
name = "reportworm-meta"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "reportworm-builder",
    "watchdog>=6.0.0",
]

[tool.uv.sources]
reportworm-builder = { git = "https://github.com/mikewVGC/reportworm-builder.git" }
